# config.yaml

sites:
  snakeden:
    name: "Snakeden Run"
    initial_release: 1578
    sampling_occasions:
      - { occasion: 0, date: "2023-07-27" }
      - { occasion: 1, date: "2024-07-25" }
      - { occasion: 2, date: "2024-08-29" }
      - { occasion: 3, date: "2024-10-10" }
      - { occasion: 4, date: "2025-03-12" }
      - { occasion: 5, date: "2025-07-17" }
      - { occasion: 6, date: "2025-08-29" }
      - { occasion: 7, date: "2025-09-19" }
      - { occasion: 8, date: "2025-09-30" }

  glade:
    name: "Glade Run"
    initial_release: 1224
    sampling_occasions:
      - { occasion: 0, date: "2023-07-26" }
      - { occasion: 1, date: "2024-07-25" }
      - { occasion: 2, date: "2024-09-08" }
      - { occasion: 3, date: "2024-10-11" }
      - { occasion: 4, date: "2025-03-12" }
      - { occasion: 5, date: "2025-07-18" }
      - { occasion: 6, date: "2025-08-29" }
      - { occasion: 7, date: "2025-09-18" }
      - { occasion: 8, date: "2025-09-29" }

# Defined ranges for importing encounter data
sheet_ranges:
  snakeden:
    - { occasion: 1, sheet: "2024 Snakeden MR", range: "S3:X323",   expected_rows: 320 }
    - { occasion: 2, sheet: "2024 Snakeden MR", range: "Z3:AE196",  expected_rows: 193 }
    - { occasion: 3, sheet: "2024 Snakeden MR", range: "AG3:AL86",  expected_rows: 83  }
    - { occasion: 4, sheet: "2024 Snakeden MR", range: "AN3:AS81",  expected_rows: 78  }
    - { occasion: 5, sheet: "2025 Snakeden MR", range: "A4:F78",    expected_rows: 74  }
    - { occasion: 6, sheet: "2025 Snakeden MR", range: "H4:K72",    expected_rows: 68  }
    - { occasion: 7, sheet: "2025 Snakeden MR", range: "O4:T78",    expected_rows: 74  }
    - { occasion: 8, sheet: "2025 Snakeden MR", range: "V4:Y66",    expected_rows: 62  }
  glade:
    - { occasion: 1, sheet: "2024 Glade MR", range: "R3:V98",    expected_rows: 95  }
    - { occasion: 2, sheet: "2024 Glade MR", range: "X3:AC159",  expected_rows: 156 }
    - { occasion: 3, sheet: "2024 Glade MR", range: "AE3:AI254", expected_rows: 251 }
    - { occasion: 4, sheet: "2024 Glade MR", range: "AK3:AP142", expected_rows: 139 }
    - { occasion: 5, sheet: "2025 Glade MR", range: "B4:G301",   expected_rows: 297 }
    - { occasion: 6, sheet: "2025 Glade MR", range: "I4:N297",   expected_rows: 293 }
    - { occasion: 7, sheet: "2025 Glade MR", range: "P4:U238",   expected_rows: 234 }
    - { occasion: 8, sheet: "2025 Glade MR", range: "W4:AB271",  expected_rows: 267 }

# Removed mussels for chester experiment
# source: 
# workbook: 2024 and 2025 MR Summary - 1.xlsx
# sheet: 2024 Glade MR
# range: AR:AX
removed_mussels_alive:
  - C700
  - B080
  - D506
  - C251
  - B635
  - B526
  - B638
  - B942
  - C954
  - O027
  - C758
  - B167
  - B170
  - B106
  - C559
  - B840
  - C379
  - B098
  - C145
  - C094
  - B090
  - B972
  - C291
  - B628
  - D412
  - C352
  - D392
  - B064
  - D434
  - C311
removed_mussels_dead:
  - D013

# Removed mussels by Brennan and Donya 
# source: 
# workbook: 2024 and 2025 MR Summary - 1.xlsx
# sheet: 2024 Snakeden MR
# range: AW:BP
b_and_d_removed_mussels:
  interval_2:
    - C630
    - B071
    - B735
    - C213
    - D091
    - B611
    - B476
    - C147
    - C876
    - D242
    - c213
    - C635
    - C366
    - C613
    - B978
    - B560
    - D125
  interval_3:
    - C903
    - B891
    - D619
    - D045
    - C825
    - C217
  unknown_interval:
    - D299
    - C006




