# config.yaml

sites:
  snakeden:
    name: "Snakeden Run"
    coord: "38.9238, -77.33168"
    initial_release: 1578
    sampling_occasions:
      - { occasion: 0, date: "2023-07-27" }
      - { occasion: 1, date: "2024-07-25" }
      - { occasion: 2, date: "2024-08-29" }
      - { occasion: 3, date: "2024-10-10" }
      - { occasion: 4, date: "2025-03-12" }
      - { occasion: 5, date: "2025-07-17" }
      - { occasion: 6, date: "2025-08-29" }
      - { occasion: 7, date: "2025-09-19" }
      - { occasion: 8, date: "2025-09-30" }

  glade:
    name: "Glade Run"
    coord: "38.93031, -77.34245"
    initial_release: 1224
    sampling_occasions:
      - { occasion: 0, date: "2023-07-26" }
      - { occasion: 1, date: "2024-07-25" }
      - { occasion: 2, date: "2024-09-08" }
      - { occasion: 3, date: "2024-10-11" }
      - { occasion: 4, date: "2025-03-12" }
      - { occasion: 5, date: "2025-07-18" }
      - { occasion: 6, date: "2025-08-29" }
      - { occasion: 7, date: "2025-09-18" }
      - { occasion: 8, date: "2025-09-29" }

# Defined ranges for importing encounter data
sheet_ranges:
  snakeden:
    - { occasion: 1, sheet: "2024 Snakeden MR", range: "S3:X323",   expected_rows: 320 }
    - { occasion: 2, sheet: "2024 Snakeden MR", range: "Z3:AE196",  expected_rows: 193 }
    - { occasion: 3, sheet: "2024 Snakeden MR", range: "AG3:AL86",  expected_rows: 83  }
    - { occasion: 4, sheet: "2024 Snakeden MR", range: "AN3:AS81",  expected_rows: 78  }
    - { occasion: 5, sheet: "2025 Snakeden MR", range: "A4:F78",    expected_rows: 74  }
    - { occasion: 6, sheet: "2025 Snakeden MR", range: "H4:K72",    expected_rows: 68  }
    - { occasion: 7, sheet: "2025 Snakeden MR", range: "O4:T78",    expected_rows: 74  }
    - { occasion: 8, sheet: "2025 Snakeden MR", range: "V4:Y66",    expected_rows: 62  }
  glade:
    - { occasion: 1, sheet: "2024 Glade MR", range: "R3:V98",    expected_rows: 95  }
    - { occasion: 2, sheet: "2024 Glade MR", range: "X3:AC159",  expected_rows: 156 }
    - { occasion: 3, sheet: "2024 Glade MR", range: "AE3:AI254", expected_rows: 251 }
    - { occasion: 4, sheet: "2024 Glade MR", range: "AK3:AP142", expected_rows: 139 }
    - { occasion: 5, sheet: "2025 Glade MR", range: "B4:G301",   expected_rows: 297 }
    - { occasion: 6, sheet: "2025 Glade MR", range: "I4:N297",   expected_rows: 293 }
    - { occasion: 7, sheet: "2025 Glade MR", range: "P4:U238",   expected_rows: 234 }
    - { occasion: 8, sheet: "2025 Glade MR", range: "W4:AB271",  expected_rows: 267 }

# Report numbers
report_variables:
  snakeden_release: 1578
  glade_release: 1224

# Removed mussels for chester experiment
# source: 
# workbook: 2024 and 2025 MR Summary - 1.xlsx
# sheet: 2024 Glade MR
# range: AR:AX
removed_mussels_alive:
  - C700
  - B080
  - D506
  - C251
  - B635
  - B526
  - B638
  - B942
  - C954
  - O027
  - C758
  - B167
  - B170
  - B106
  - C559
  - B840
  - C379
  - B098
  - C145
  - C094
  - B090
  - B972
  - C291
  - B628
  - D412
  - C352
  - D392
  - B064
  - D434
  - C311
removed_mussels_dead:
  - D013

# Removed mussels by Brennan and Donya 
# source: 
# workbook: 2024 and 2025 MR Summary - 1.xlsx
# sheet: 2024 Snakeden MR
# range: AW:BP
b_and_d_removed_mussels:
  interval_2:
    - C630
    - B071
    - B735
    - C213
    - D091
    - B611
    - B476
    - C147
    - C876
    - D242
    - c213
    - C635
    - C366
    - C613
    - B978
    - B560
    - D125
  interval_3:
    - C903
    - B891
    - D619
    - D045
    - C825
    - C217
  unknown_interval:
    - D299
    - C006

# Removed mussels for experiments 
# source: 
# workbook: Sacrificed & Random Dead Mussels 2023-2025.xlsx
# sheet: Sheet1
# range: A:E
experiment_removal:
  glade_experiment_removal:
    - D412
    - B635
    - C954
    - C291
    - B064
    - B972
    - B942
    - C379
    - B106
    - C145
    - C311
    - B098
    - B170
    - C251
    - C700
    - B628
    - O027
    - C526
    - B080
    - B840
    - C352
    - D392
    - B090
    - C094
    - B161
    - B417
    - C568
    - B833
    - D540
    - B070
    - C335
    - C394
    - B470
    - B984
    - B137
    - B622
    - B999
    - C261
    - C102
    - B434
    - B886
    - D437
    - D477
    - B066
    - B670
    - B870
    - C430
    - B114
    - B672
    - B835
    - C495
    - B583
    - C908
    - C389
    - B443
    - C444
    - C299
    - B640
    - C528
    - C889
    - B704
    - C448
    - B065
    - B054
  snakeden_experiment_removal:
    - D171
    - D713
    - C225
    - D689
    - D289
    - C134
    - D143
    - D195
    - C120
    - B970
    - B900
    - D775
    - D055
    - C089
    - B398
    - D264
    - B775
    - B790
    - C322
    - B909
    - B645
    - B326
    - B183
    - B777
    - C059
    - B847
    - B615
    - B331
    - B949
    - B715
    - D801
    - B252
    - D685
    - B736
    - B819
    - B268
    - C374
    - C659
    - D662
    - B468
    - B147
    - B105
    - B201
    - B910
    - B853
    - B346
    - B274
    - C416
    - D187
    - C035
    - C714
    - B453
    - B706
    - D756
    - C828
    - C046
    - B205
    - C180
    - B574
    - C244
    - B338
    - C099
# Unknown reasons for removal 
# source: 
# workbook: Sacrificed & Random Dead Mussels 2023-2025.xlsx
# sheet: Sheet1
# range: A:E
unknown_removal:
  interval_2:
    - B335
    - B748
    - B875
    - C186
    - C411
    - C637
    - C676
    - D103
    - D169
    - D198
  interval_3:
    - B498
    - D059
    - D073
    - D257
    - D710
    - B374
    - C369
    - B228
    - B446
    - C623
    - D777
  interval_4:
    - B751
    - B811
    - C124
    - C811
    - C854
    - D142
    - D210
    - B280
    - B499
    - B569
    - B597
    - B841
    - C137
    - C616
    - C633
    - D189
    - D266
    - D267
    - D300
    - D788





